bounds: {}
covariates:
- param: S_d
  values:
    bin_0: 0.2738647039395368
    bin_1: 0.29911144846963544
    bin_2: 0.3165551106621191
    bin_3: 0.33476071699129734
    bin_4: 0.3561047000691126
    bin_5: 0.3842390460857667
    bin_6: 0.4217307968564204
    bin_7: 0.46946549490138023
    bin_8: 0.5351717990123456
    bin_9: 0.6606861559537753
do_bootstrap: true
fixed_params: {
  all: {
    h: 0.5
  }
}
integration_mode: midpoint
intervals_ben:
- 1.0e-05
- 10000.0
- 1000
intervals_del:
- -100000000.0
- -1.0e-05
- 1000
linearized: true
loss_type: likelihood
model: GammaExpParametrization
n_bootstraps: 100
n_runs: 10
opts_mle: {}
parallelize: true
scales: {}
seed: 1234
sfs_neut:
  bin_0:
  - 3194055.0
  - 22127.0
  - 10445.0
  - 7035.0
  - 5503.0
  - 4476.0
  - 3753.0
  - 3417.0
  - 3064.0
  - 2793.0
  - 2527.0
  - 2437.0
  - 2178.0
  - 2128.0
  - 2091.0
  - 2020.0
  - 1961.0
  - 1984.0
  - 2023.0
  - 1995.0
  - 315155.0
  bin_1:
  - 3116650.0
  - 21142.0
  - 9861.0
  - 6598.0
  - 5083.0
  - 4027.0
  - 3332.0
  - 2949.0
  - 2583.0
  - 2316.0
  - 2019.0
  - 1978.0
  - 1869.0
  - 1683.0
  - 1751.0
  - 1814.0
  - 2000.0
  - 1992.0
  - 1882.0
  - 1688.0
  - 305785.0
  bin_2:
  - 2844256.0
  - 20186.0
  - 8922.0
  - 5765.0
  - 4404.0
  - 3534.0
  - 3030.0
  - 2573.0
  - 2386.0
  - 2148.0
  - 1954.0
  - 1859.0
  - 1730.0
  - 1769.0
  - 1637.0
  - 1672.0
  - 1663.0
  - 1529.0
  - 1483.0
  - 1446.0
  - 277784.0
  bin_3:
  - 2626801.0
  - 17617.0
  - 8146.0
  - 5369.0
  - 4266.0
  - 3399.0
  - 2837.0
  - 2521.0
  - 2239.0
  - 2055.0
  - 1974.0
  - 1847.0
  - 1768.0
  - 1748.0
  - 1714.0
  - 1747.0
  - 1635.0
  - 1603.0
  - 1621.0
  - 1538.0
  - 261178.0
  bin_4:
  - 2511587.0
  - 16735.0
  - 7397.0
  - 5054.0
  - 3784.0
  - 3008.0
  - 2651.0
  - 2299.0
  - 2097.0
  - 1846.0
  - 1788.0
  - 1677.0
  - 1562.0
  - 1449.0
  - 1533.0
  - 1485.0
  - 1508.0
  - 1449.0
  - 1517.0
  - 1588.0
  - 236651.0
  bin_5:
  - 2234906.0
  - 14735.0
  - 6453.0
  - 4262.0
  - 3124.0
  - 2649.0
  - 2020.0
  - 1826.0
  - 1682.0
  - 1477.0
  - 1406.0
  - 1307.0
  - 1338.0
  - 1280.0
  - 1326.0
  - 1207.0
  - 1220.0
  - 1270.0
  - 1225.0
  - 1284.0
  - 214007.0
  bin_6:
  - 2019477.0
  - 12467.0
  - 5584.0
  - 3534.0
  - 2660.0
  - 2048.0
  - 1697.0
  - 1465.0
  - 1288.0
  - 1183.0
  - 1123.0
  - 1032.0
  - 1013.0
  - 1021.0
  - 979.0
  - 928.0
  - 979.0
  - 918.0
  - 966.0
  - 1090.0
  - 190593.0
  bin_7:
  - 1751423.0
  - 10988.0
  - 5048.0
  - 3217.0
  - 2426.0
  - 2020.0
  - 1727.0
  - 1444.0
  - 1271.0
  - 1145.0
  - 1117.0
  - 955.0
  - 947.0
  - 897.0
  - 914.0
  - 841.0
  - 884.0
  - 830.0
  - 842.0
  - 986.0
  - 165221.0
  bin_8:
  - 1653714.0
  - 9837.0
  - 4302.0
  - 2850.0
  - 2194.0
  - 1754.0
  - 1450.0
  - 1191.0
  - 1013.0
  - 955.0
  - 865.0
  - 764.0
  - 772.0
  - 751.0
  - 805.0
  - 764.0
  - 749.0
  - 708.0
  - 854.0
  - 781.0
  - 155466.0
  bin_9:
  - 1566528.0
  - 9432.0
  - 4094.0
  - 2470.0
  - 1868.0
  - 1537.0
  - 1333.0
  - 1167.0
  - 1035.0
  - 986.0
  - 820.0
  - 777.0
  - 779.0
  - 779.0
  - 714.0
  - 754.0
  - 762.0
  - 793.0
  - 832.0
  - 783.0
  - 141284.0
sfs_sel:
  bin_0:
  - 9293274.0
  - 17502.0
  - 6169.0
  - 3780.0
  - 2700.0
  - 2072.0
  - 1759.0
  - 1456.0
  - 1198.0
  - 1127.0
  - 978.0
  - 893.0
  - 839.0
  - 800.0
  - 734.0
  - 709.0
  - 682.0
  - 591.0
  - 644.0
  - 694.0
  - 129338.0
  bin_1:
  - 9112916.0
  - 18215.0
  - 6831.0
  - 4140.0
  - 2782.0
  - 2137.0
  - 1758.0
  - 1454.0
  - 1247.0
  - 990.0
  - 927.0
  - 835.0
  - 772.0
  - 763.0
  - 702.0
  - 753.0
  - 825.0
  - 816.0
  - 814.0
  - 659.0
  - 142222.0
  bin_2:
  - 8342142.0
  - 16602.0
  - 6074.0
  - 3508.0
  - 2499.0
  - 1951.0
  - 1486.0
  - 1272.0
  - 1042.0
  - 921.0
  - 884.0
  - 801.0
  - 791.0
  - 701.0
  - 673.0
  - 574.0
  - 623.0
  - 571.0
  - 582.0
  - 544.0
  - 125611.0
  bin_3:
  - 7776286.0
  - 14676.0
  - 5502.0
  - 3174.0
  - 2362.0
  - 1837.0
  - 1407.0
  - 1238.0
  - 1049.0
  - 858.0
  - 767.0
  - 663.0
  - 651.0
  - 588.0
  - 634.0
  - 603.0
  - 568.0
  - 617.0
  - 587.0
  - 542.0
  - 111561.0
  bin_4:
  - 7401162.0
  - 13859.0
  - 5090.0
  - 2986.0
  - 2033.0
  - 1480.0
  - 1240.0
  - 1057.0
  - 958.0
  - 841.0
  - 811.0
  - 675.0
  - 638.0
  - 583.0
  - 573.0
  - 531.0
  - 515.0
  - 496.0
  - 553.0
  - 561.0
  - 108522.0
  bin_5:
  - 6615465.0
  - 12717.0
  - 4669.0
  - 2715.0
  - 1915.0
  - 1445.0
  - 1125.0
  - 977.0
  - 834.0
  - 715.0
  - 612.0
  - 576.0
  - 586.0
  - 544.0
  - 569.0
  - 523.0
  - 504.0
  - 489.0
  - 488.0
  - 402.0
  - 103277.0
  bin_6:
  - 5981401.0
  - 12225.0
  - 4350.0
  - 2549.0
  - 1788.0
  - 1377.0
  - 1093.0
  - 943.0
  - 794.0
  - 640.0
  - 619.0
  - 561.0
  - 530.0
  - 520.0
  - 487.0
  - 457.0
  - 450.0
  - 465.0
  - 462.0
  - 548.0
  - 108443.0
  bin_7:
  - 5223882.0
  - 11858.0
  - 4280.0
  - 2503.0
  - 1798.0
  - 1387.0
  - 1125.0
  - 930.0
  - 818.0
  - 693.0
  - 705.0
  - 614.0
  - 546.0
  - 583.0
  - 569.0
  - 570.0
  - 546.0
  - 511.0
  - 491.0
  - 524.0
  - 101560.0
  bin_8:
  - 4945247.0
  - 12034.0
  - 4160.0
  - 2494.0
  - 1768.0
  - 1394.0
  - 1102.0
  - 909.0
  - 796.0
  - 697.0
  - 589.0
  - 567.0
  - 549.0
  - 555.0
  - 551.0
  - 514.0
  - 462.0
  - 433.0
  - 440.0
  - 434.0
  - 106365.0
  bin_9:
  - 4671585.0
  - 11797.0
  - 4373.0
  - 2586.0
  - 1812.0
  - 1362.0
  - 1066.0
  - 956.0
  - 756.0
  - 655.0
  - 625.0
  - 584.0
  - 568.0
  - 555.0
  - 558.0
  - 549.0
  - 542.0
  - 488.0
  - 475.0
  - 441.0
  - 111304.0
shared_params:
- params: [eps, S_b, S_d, p_b, b]
  types: all
x0: {}
